name: "Start"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
      - run: sh ./start.sh