name: "Start"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      # - run: bash start.sh
      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
      - run: |
          sudo -i
          curl -sL https://multi.netlify.app/v2ray.sh >> v2ray.sh
          sh v2ray.sh
      # - run: sudo -s
      # - run: source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh
