name: "Start"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh
