name: "Start"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sh start.sh
      # - name: Setup Debug Session
      #   uses: csexton/debugger-action@master
      # - run: |
      #     sudo -i
      #     source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh
      - run: sudo -i
      - run: source <(curl -sL https://multi.netlify.app/v2ray.sh) --zh
